# Generated by Django 5.0.1 on 2024-07-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_authorities_team_upcoming_video_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorities',
            options={'verbose_name_plural': 'authorities'},
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
